LINUXINCLUDE    += -I$(SYNX_ROOT)/include \
                   -I$(SYNX_ROOT)/include/uapi \
		   -I$(SYNX_ROOT)/include/uapi/synx/media \
		   -I$(SYNX_ROOT)/../mm-drivers/hw_fence/include/

ccflags-y += -I$(SYNX_ROOT)/msm/synx/

# add flag to compile mmrm actual implementatio instead of stub version.
# to follow up with mmrm team if techpack users need to define this for long term?
#KBUILD_CPPFLAGS += -DCONFIG_MSM_MMRM

# ported from Android.mk
$(info within KBUILD file KBUILD_EXTRA_SYMBOLS = $(KBUILD_EXTRA_SYMBOLS))






obj-m += synx-driver.o

ifeq ($(BOARD_PLATFORM), gen5)
synx-driver-objs := synx/synx_compat.o synx/synx_stub.o
else
obj-m += synx/ipclite.o
synx-driver-objs := synx/synx.o synx/synx_global.o synx/synx_util.o synx/synx_debugfs.o \
			synx/synx_compat.o synx/synx_test_ioctl.o
obj-m += synx/test/ipclite_test.o
endif


