LINUXINCLUDE    += -I$(SYNX_ROOT)/include \
                   -I$(SYNX_ROOT)/include/uapi \
				   -I$(SYNX_ROOT)/include/uapi/synx/media

ccflags-y += -I$(SYNX_ROOT)/msm/synx/

# add flag to compile mmrm actual implementatio instead of stub version.
# to follow up with mmrm team if techpack users need to define this for long term?
#KBUILD_CPPFLAGS += -DCONFIG_MSM_MMRM

# ported from Android.mk
$(info within KBUILD file KBUILD_EXTRA_SYMBOLS = $(KBUILD_EXTRA_SYMBOLS))

ifeq ($(CONFIG_ARCH_ANORAK), y)
$(info within KBUILD file CONFIG_ARCH_ANORAK = $(CONFIG_ARCH_ANORAK))
# include $(SYNX_ROOT)/config/anorak61.mk
KBUILD_CPPFLAGS += -DCONFIG_SYNX_ANORAK=1
ccflags-y += -DCONFIG_SYNX_ANORAK=1
endif

obj-m += synx/ipclite.o
obj-m += synx-driver.o
synx-driver-objs := synx/synx.o synx/synx_global.o synx/synx_util.o synx/synx_debugfs.o

