# SPDX-License-Identifier: GPL-2.0-only

obj-m += synx-driver.o

# synx-kernel module only includes interface layer files
synx-driver-objs := synx/synx_compat.o synx/synx_ioctl.o synx/synx_stub.o \
					synx/synx_compat_debug.o synx/synx_test_ioctl.o
